2021-07-29 12:23:38,798 ERROR: Exception on / [GET] [in g:\intercloud\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\intercloud\flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "G:\Intercloud\flask\microblog\app\main\routes.py", line 44, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "g:\intercloud\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "g:\intercloud\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\Intercloud\flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "G:\Intercloud\flask\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "G:\Intercloud\flask\microblog\app\templates\base.html", line 24, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "g:\intercloud\flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\intercloud\flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "g:\intercloud\flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2021-07-29 12:34:02,132 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:77]
2021-07-29 12:34:42,122 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:77]
2021-07-29 12:34:50,134 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:77]
2021-07-29 13:35:10,659 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:35:18,491 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:36:25,520 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:36:36,675 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:36:36,675 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:39:59,341 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:40:09,097 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:40:30,510 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:40:30,510 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:42:59,104 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:43:37,349 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:43:37,349 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:48:22,765 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:58:42,205 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:59:04,743 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 13:59:04,743 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 14:10:45,088 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 14:11:15,090 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 14:11:15,090 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 14:14:29,903 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
2021-07-29 14:59:02,142 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:81]
